# Site settings
title: Shown's blog
SEOTitle: Welocme to Shown's blog
header-img: img/post-bg-desk.jpg
email: bieshixuan@163.com
description: "Learning... Codeing..."
keyword: "Shown, ShownBie, poos, iOS, Apple, iPhone"
url: "https://poos.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/poos/poos.github.io.git" # you code repository


# Publish posts or collection documents with a future date.
future: true


# SNS settings
RSS: false
weibo_username:     poos_github.io
#zhihu_username:     poos
github_username:    poos
#facebook_username:  poos
#jianshu_username:   poos
#twitter_username:   poos


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1




# Disqus settings
disqus_username: poos

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-Me.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: b9f52202894099af76ae                            #生成的clientID
  clientSecret: 6772b808e9c731d2f58fe1754947778cbe8833ab    #生成的clientSecret
  repo: poos.github.io    #仓库名称
  owner: poos    #github用户名
  admin: poos
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Friends
friends: [
    {
        title: "github/poos",
        href: "https://github.com/poos"
    },{
        title: "gitee/poos",
        href: "https://gitee.com/poos"
    },
    {
        title: "oschina/bieshixuan",
        href: "https://my.oschina.net/bieshixuan"
    }
]
